type Duration = string

export type MetaData = {
  date: Date
  type: string
  algorithm: string
  location: string
  latitude: string
  longitude: string
  elevation: string
  timeZoneName: string
  timeZoneID: string
  timeZoneOffset: string
}

type Zmanim = {
  Alos120Zmanis: Date
  Alos120: Date
  Alos26Degrees: Date
  Alos96Zmanis: Date
  Alos96: Date
  Alos90Zmanis: Date
  Alos90: Date
  Alos19Point8Degrees: Date
  Alos19Degrees: Date
  Alos18Degrees: Date
  BeginAstronomicalTwilight: Date
  Alos72Zmanis: Date
  Alos72: Date
  AlosBaalHatanya: Date
  Alos16Point1Degrees: Date
  AlosHashachar: Date
  Alos60: Date
  BeginNauticalTwilight: Date
  Misheyakir11Point5Degrees: Date
  Misheyakir11Degrees: Date
  Misheyakir10Point2Degrees: Date
  Misheyakir9Point5Degrees: Date
  Misheyakir7Point65Degrees: Date
  BeginCivilTwilight: Date
  SeaLevelSunrise: Date
  Sunrise: Date
  SofZmanShmaMGA120Minutes: Date
  SofZmanShmaAlos16Point1ToSunset: Date
  SofZmanShmaMGA96MinutesZmanis: Date
  SofZmanShmaMGA96Minutes: Date
  SofZmanShmaMGA90MinutesZmanis: Date
  SofZmanShmaMGA90Minutes: Date
  SofZmanShmaAteretTorah: Date
  SofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees: Date
  SofZmanShmaMGA19Point8Degrees: Date
  SofZmanShmaMGA18Degrees: Date
  SofZmanShmaMGA72MinutesZmanis: Date
  SofZmanShmaMGA: Date
  SofZmanShmaMGA72Minutes: Date
  SofZmanShmaMGA16Point1Degrees: Date
  SofZmanShmaBaalHatanya: Date
  SofZmanShmaGRA: Date
  SofZmanShmaKolEliyahu: Date
  SofZmanShma3HoursBeforeChatzos: Date
  SofZmanShmaFixedLocal: Date
  SofZmanTfilaMGA120Minutes: Date
  SofZmanTfilahAteretTorah: Date
  SofZmanTfilaMGA96MinutesZmanis: Date
  SofZmanTfilaMGA96Minutes: Date
  SofZmanTfilaMGA90MinutesZmanis: Date
  SofZmanTfilaMGA90Minutes: Date
  SofZmanTfilaMGA19Point8Degrees: Date
  SofZmanTfilaMGA18Degrees: Date
  SofZmanTfilaMGA72MinutesZmanis: Date
  SofZmanAchilasChametzMGA72Minutes: Date
  SofZmanTfilaMGA: Date
  SofZmanTfilaMGA72Minutes: Date
  SofZmanAchilasChametzMGA16Point1Degrees: Date
  SofZmanTfilaMGA16Point1Degrees: Date
  SofZmanAchilasChametzBaalHatanya: Date
  SofZmanTfilaBaalHatanya: Date
  SofZmanAchilasChametzGRA: Date
  SofZmanTfilaGRA: Date
  SofZmanTfila2HoursBeforeChatzos: Date
  SofZmanTfilaFixedLocal: Date
  SofZmanBiurChametzMGA72Minutes: Date
  SofZmanBiurChametzMGA16Point1Degrees: Date
  SofZmanBiurChametzBaalHatanya: Date
  SofZmanBiurChametzGRA: Date
  Chatzos: Date
  SunTransit: Date
  FixedLocalChatzos: Date
  MinchaGedolaAteretTorah: Date
  MinchaGedola30Minutes: Date
  MinchaGedola: Date
  MinchaGedolaGreaterThan30: Date
  MinchaGedolaBaalHatanya: Date
  MinchaGedolaBaalHatanyaGreaterThan30: Date
  MinchaGedola16Point1Degrees: Date
  MinchaGedola72Minutes: Date
  MinchaKetana: Date
  MinchaKetanaBaalHatanya: Date
  MinchaKetanaAteretTorah: Date
  MinchaKetana16Point1Degrees: Date
  MinchaKetana72Minutes: Date
  PlagAlosToSunset: Date
  PlagHamincha: Date
  PlagHaminchaBaalHatanya: Date
  PlagAlos16Point1ToTzaisGeonim7Point083Degrees: Date
  PlagHaminchaAteretTorah: Date
  PlagHamincha60Minutes: Date
  PlagHamincha16Point1Degrees: Date
  PlagHamincha72Minutes: Date
  PlagHamincha72MinutesZmanis: Date
  BainHasmashosYereim18Minutes: Date
  CandleLighting: Date
  BainHasmashosYereim16Point875Minutes: Date
  BainHasmashosYereim2Point99Degrees: Date
  PlagHamincha18Degrees: Date
  BainHasmashosYereim2Point8Degrees: Date
  BainHasmashosYereim13Point5Minutes: Date
  BainHasmashosYereim2Point1Degrees: Date
  PlagHamincha19Point8Degrees: Date
  PlagHamincha90Minutes: Date
  PlagHamincha90MinutesZmanis: Date
  SeaLevelSunset: Date
  Sunset: Date
  PlagHamincha96Minutes: Date
  PlagHamincha96MinutesZmanis: Date
  PlagHamincha26Degrees: Date
  TzaisGeonim3Point65Degrees: Date
  TzaisGeonim3Point676Degrees: Date
  TzaisGeonim3Point7Degrees: Date
  TzaisGeonim3Point8Degrees: Date
  BainHasmashosRT13Point5MinutesBefore7Point083Degrees: Date
  TzaisGeonim4Point37Degrees: Date
  TzaisGeonim4Point61Degrees: Date
  TzaisGeonim4Point8Degrees: Date
  PlagHamincha120Minutes: Date
  PlagHamincha120MinutesZmanis: Date
  TzaisGeonim5Point88Degrees: Date
  TzaisGeonim5Point95Degrees: Date
  EndCivilTwilight: Date
  TzaisBaalHatanya: Date
  BainHasmashosRT2Stars: Date
  TzaisGeonim6Point45Degrees: Date
  TzaisGeonim7Point083Degrees: Date
  TzaisGeonim7Point67Degrees: Date
  Tzais: Date
  TzaisGeonim8Point5Degrees: Date
  TzaisGeonim9Point3Degrees: Date
  TzaisGeonim9Point75Degrees: Date
  TzaisAteretTorah: Date
  EndNauticalTwilight: Date
  BainHasmashosRT13Point24Degrees: Date
  BainHasmashosRT58Point5Minutes: Date
  Tzais60: Date
  Tzais16Point1Degrees: Date
  Tzais72: Date
  Tzais72Zmanis: Date
  EndAstronomicalTwilight: Date
  Tzais18Degrees: Date
  Tzais19Point8Degrees: Date
  Tzais90: Date
  Tzais90Zmanis: Date
  Tzais96: Date
  Tzais96Zmanis: Date
  Tzais26Degrees: Date
  Tzais120: Date
  Tzais120Zmanis: Date
  SolarMidnight: Date
  ShaahZmanisGra: Duration
  TemporalHour: Duration
  ShaahZmanisBaalHatanya: Duration
  ShaahZmanisAteretTorah: Duration
  ShaahZmanis60Minutes: Duration
  ShaahZmanis16Point1Degrees: Duration
  ShaahZmanis72Minutes: Duration
  ShaahZmanisMGA: Duration
  ShaahZmanis72MinutesZmanis: Duration
  ShaahZmanis18Degrees: Duration
  ShaahZmanis19Point8Degrees: Duration
  ShaahZmanis90Minutes: Duration
  ShaahZmanis90MinutesZmanis: Duration
  ShaahZmanis96Minutes: Duration
  ShaahZmanis96MinutesZmanis: Duration
  ShaahZmanis26Degrees: Duration
  ShaahZmanis120Minutes: Duration
  ShaahZmanis120MinutesZmanis: Duration
  SofZmanKidushLevana15Days: string
  SofZmanKidushLevanaBetweenMoldos: string
  TchilasZmanKidushLevana3Days: string
  TchilasZmanKidushLevana7Days: string
  ZmanMolad: string
}

export interface ZmanimData {
  zmanim: {
    metadata: MetaData
    Zmanim: Zmanim
    BasicZmanim: Partial<Zmanim>
  }
}
